/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.logic.UsuarioLOGIC;

/**
 *
 * @author Fabricio Rios
 */
public class FMLogin extends javax.swing.JFrame {

    /**
     * Creates new form FMLogin
     */
    public FMLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        btnlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPF_contrasenia = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        CBmostrarcontrasenia = new javax.swing.JCheckBox();
        btnlogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btncrearusuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(36, 75, 197));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(36, 75, 197));
        txtUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setOpaque(true);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 250, 30));

        btnlabel.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btnlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabel.setText("Login");
        btnlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.add(btnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sports_esports.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        JPF_contrasenia.setBackground(new java.awt.Color(36, 75, 197));
        JPF_contrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JPF_contrasenia.setBorder(null);
        JPF_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_contraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(JPF_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 240, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Username.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        CBmostrarcontrasenia.setText("Mostrar contraseña");
        CBmostrarcontrasenia.setToolTipText("");
        CBmostrarcontrasenia.setBorder(null);
        CBmostrarcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmostrarcontraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(CBmostrarcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login btn.png"))); // NOI18N
        btnlogin.setBorder(null);
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 300, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Crear usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Password (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        btncrearusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button.png"))); // NOI18N
        btncrearusuario.setBorder(null);
        btncrearusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btncrearusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Vector (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 400, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        if (!txtUsuario.getText().isEmpty() && !JPF_contrasenia.getText().isEmpty()) {
            if (UsuarioLOGIC.autentificar(txtUsuario.getText(), JPF_contrasenia.getText())) {
                JOptionPane.showMessageDialog(this, "Bienvenido disfrute");
                this.dispose();
               
                FRMPaginaPrincipal paginaPrincipal = new FRMPaginaPrincipal(UsuarioLOGIC.obtener(txtUsuario.getText()));
                paginaPrincipal.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Falta ingresar usuario o contraseña");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void JPF_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPF_contraseniaActionPerformed

    private void CBmostrarcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmostrarcontraseniaActionPerformed

       if(CBmostrarcontrasenia.isSelected() == true){
           JPF_contrasenia.setEchoChar((char)0);
       }else if(CBmostrarcontrasenia.isSelected() == false){
           JPF_contrasenia.setEchoChar('*');
       }
    }//GEN-LAST:event_CBmostrarcontraseniaActionPerformed

    private void btncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearusuarioActionPerformed
        FRMRegistrarUsuario registrarusuario = new FRMRegistrarUsuario(this,true);
        registrarusuario.setVisible(true);
    }//GEN-LAST:event_btncrearusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBmostrarcontrasenia;
    private javax.swing.JPasswordField JPF_contrasenia;
    private javax.swing.JButton btncrearusuario;
    private javax.swing.JLabel btnlabel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
